### ISSUE TITLE
qiime not successfully installed (Linux)

### ISSUE THREAD

**Issue by BCArg** [aomlomics/tourmaline#104]
Dear Luke,

I am trying to install the tourmaline pipeline native on linux. I have downloaded the `.yml` file from `https://data.qiime2.org/distro/core/qiime2-2023.2-py38-linux-conda.yml`, but it appears the `qiime` installation was not successful.

I activate the environment, I get:
```
QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
Illegal instruction (core dumped)
```

and when I try to invoke `qiime`  I get the same error.

Can it be that this issue is related to the dependencies/ versions specified on the `.yml` file that I used to build the environment?

Just out of curiosity, I checked on conda and there is already a new version of qiime2: https://anaconda.org/qiime2/qiime2. I tried downloading the env from [this url](https://raw.githubusercontent.com/qiime2/environment-files/master/2023.5/release/qiime2-2023.5-py38-linux-conda.yml), but still got the same error

Below is the complete information on my OS
```
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Thanks in advance

**Comment by ksilnoaa** [comment]
@BCArg, this seems like a Qiime issue that can happen on Ubuntu:  
https://forum.qiime2.org/t/qiime-is-caching-your-current-deployment-illegal-instruction-core-dumped/26028/11

I recommend checking out the qiime forum and seeing if they can resolve your issue.
