### ISSUE TITLE
Create table of number of reads retained per sample at each step

### ISSUE THREAD

**Issue by lukenoaa** [aomlomics/tourmaline#128]
DADA2 in R provides this and it's very convenient to see what each step is doing

**Comment by ksilnoaa** [comment]
There is a rule to do this (summarize_repseqs), but it's output is not listed under a pseudo-rule so it is not done by default.

**Comment by lukenoaa** [comment]
Is there any reason not to run this rule by default? If not I'll go ahead and add it. (The generally philosophy of Tourmaline is that all rules will be run if the main pseudo-rules are run.)

**Comment by ksilnoaa** [comment]
No I think that was an oversight on my part in the early days. Go ahead and add it.

**Comment by ksilnoaa** [comment]
This was made default in V2, through files "stats/dada2_stats.qza" and "dada2_stats.qzv"
