### ISSUE TITLE
Unzip of table.biom and representative_sequences.fasta causes breaks process when parallelizing

### ISSUE THREAD

**Issue by richardsm32** [aomlomics/tourmaline#15]
I have been using the --cores __ argument in snakemake for dada2_pe_denoise and consistently had non-zero exit statuses for unzip rules which invoke commands like unzip, mv, and rm. After my own debugging I have found that this is because of a race condition on the temp folder. Multiple processes are trying to write/unzip/delete the folder. Creating a separate folder for each rule seemed to fix this (temp0, temp1, etc.). Please consider modifying the Snakefile to improve parallel performance and stability.

```
    shell:
        "mkdir temp0; "
        "unzip -o {input} -d temp0; "
        "mv -v temp0/*/data/feature-table.biom {output}; "
        "rm -rf temp0; "
```

**Comment by lukenoaa** [comment]
Thanks @richardsm32! I haven't had a chance to test parallelization yet. I will look into this.

**Comment by Yixiangzhang1996** [comment]
Using shell: /usr/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:。。。。。。。

> Thanks @richardsm32! I haven't had a chance to test parallelization yet. I will look into this.

I checked the config.yaml and Snakemake files，The parameter to increase the number of CPUs was not found.In which file do you define the use of only one CPU?

**Comment by lukenoaa** [comment]
Thanks for the feedback, @Yixiangzhang1996! We've had some issues getting parallelization to work with Snakemake, but there are some more things we can try. I'm hoping to address that this week. @nvpatin

**Comment by Yixiangzhang1996** [comment]
> Thanks for the feedback, @Yixiangzhang1996! We've had some issues getting parallelization to work with Snakemake, but there are some more things we can try. I'm hoping to address that this week. @nvpatin

Very well, another thing I'd like to suggest is the documentation of input data types and reference sequences of recommended database species comments. For example, the recommended value of PE250 sequence dada2pe_trunc_len_f/r, and if the sequence species have primer sequence dada2pe_trim_left_f/r parameters should be set according to the length of primers (and even some reads have barcodes). In addition, the reference sequence selection in the Taxonomy step, I suggest adding some reference databases corresponding to the variable area in the Readme, which can improve the flexibility of the tool. If you have anything I need to test, I'd be happy to help.​

**Comment by lukenoaa** [comment]
Fixed issue raised by @richardsm32. Will create new issue for @Yixiangzhang1996's suggestion.
