### ISSUE TITLE
Output a yaml report on bioinformatics that matched edna_checklist

### ISSUE THREAD

**Issue by ksilnoaa** [aomlomics/tourmaline#157]
When uploading a Tourmaline run to NODE, we want to also provide details on the bioinformatics, and that would be most helpfulif formatted using miwa's terms.

**Comment by lukenoaa** [comment]
Great idea! I've been thinking something similar for the BeBOP protocols. Sammy is going to start working on this. I've made an issue here: https://github.com/aomlomics/protocols/issues/11
