### ISSUE TITLE
New Muscle version is not backward compatible

### ISSUE THREAD

**Issue by lukenoaa** [aomlomics/tourmaline#77]
Grant said: I ran into an error on the sequence alignment step, and the culprit was the muscle package. After a little digging, it turns out that a couple of arguments have changed in muscle since it moved to v5 (https://drive5.com/muscle5/manual/commands.html). After downgrading to Muscle v3.8.31 manually, everything worked fine, but the Anaconda package manager downloads v5.1 by default. 

"-in" has changed to "-align", "-out" has changed to "-output", "-maxiters" has changed to "-consiters" and there doesn't appear to be a diagonal optimization option in the most recent version (So, no "-diag"). When I made these changes to the snakefile, it worked fine with muscle v5.1. Chances are, you may already know about this, but I thought I should let you know regardless!

**Comment by ksilnoaa** [comment]
This was fixed in the qiime2-2023.2 Tourmaline version. Once we move to that version I will close this issue.
