### ISSUE TITLE
building with Qiime2-2022.2 py38 fails on dependencies

### ISSUE THREAD

**Issue by splaisan** [aomlomics/tourmaline#78]
Hi,
I tried to install using the current qiime2 version but it failed due to icu version conflict.
Any chance you will produce an install scenario for python38 and the current qiime2 package?
Thanks in advance

**Comment by lukenoaa** [comment]
Hello. Thanks for the suggestion. I would like to update the installation to support the latest version of QIIME 2. Unfortunately, as you discovered, there are some dependencies that don't work with Python 3.8. I haven't yet found a solution. I hope to resolve this soon. Meanwhile, you can use the working version with qiime2-2021.2, either with the native installation or Docker container.

**Comment by splaisan** [comment]
Hi Luke,
thanks for your answer, I reverted to the 2021.2 build as you propose, waiting for a later upgrade.
Thanks for the great pipeline
Best regards
