### ISSUE TITLE
Add snakemake rule to filter out samples 

### ISSUE THREAD

**Issue by ksilnoaa** [aomlomics/tourmaline#84]
It may be useful to filter out samples that did not sequence well, have contamination, or are missing certain metadata during the `filtered` steps before running the `diversity` and `report` steps. This could be implemented in a similar way as feature filtering is implemented, by providing a list of samples to exclude or filtering based on some stat (e.g., number of repseqs).

**Comment by lukenoaa** [comment]
This feature was added in the qiime2-2023.2 version.
