### ISSUE TITLE
Install all R packages through conda

### ISSUE THREAD

**Issue by lukenoaa** [aomlomics/tourmaline#99]
Also:
- Update installation instructions
- Coordinate this with environment YAML file (issue #86)

**Comment by ksilnoaa** [comment]
This worked successfully with the qiime2-2023.2 version. 

```
conda install -c bioconda bioconductor-msa bioconductor-odseq
```

**Comment by lukenoaa** [comment]
Thank you! I will test the installation on my Intel Mac.
